services:
    db:
        container_name: mydb
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root      
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: messages
        healthcheck:  # sanity check de MySQL
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
        volumes:
            - mysql_data:/var/lib/mysql  # Almacena datos de MySQL
            - ./init-scripts:/docker-entrypoint-initdb.d  # Script de inicialización
        ports:
            - "32001:3306"  
        networks:
            - mynetwork


    namenode:
        build:
            context: .
            dockerfile: hadoop.Dockerfile
        container_name: namenode
        hostname: namenode
        environment:
            - HDFS_NAMENODE_USER=hdfs
            - HDFS_DATANODE_USER=hdfs
            - HDFS_SECONDARYNAMENODE_USER=hdfs
            - CLUSTER_NAME=hadoop-cluster
            - HDFS_NAMENODE_USER=root
            - HADOOP_SSH_OPTS="-o StrictHostKeyChecking=no"
        volumes:
            - ./hadoop/namenode/data:/hadoop/dfs/name
        ports:
            - "9870:9870" # NameNode Web UI
            - "9000:9000" # NameNode RPC
        networks:
            - hadoop-network
    

    datanode:
        build:
            context: .
            dockerfile: hadoop.Dockerfile
        container_name: datanode
        hostname: datanode
        environment:
            - HDFS_NAMENODE_USER=hdfs
            - HDFS_DATANODE_USER=hdfs
            - HDFS_SECONDARYNAMENODE_USER=hdfs
        volumes:
            - ./hadoop/datanode/data:/hadoop/dfs/data
        ports:
            - "9864:9864" # DataNode Web UI
        networks:
            - hadoop-network


    hive:
        image: apache/hive:3.1.3
        container_name: hive
        environment:
            - HIVE_METASTORE_URI=thrift://postgres:9083
            - HADOOP_HOME=/opt/hadoop
        ports:
            - "10000:10000"  # Hive server2 port
            - "9083:9083"    # Hive Metastore port
        depends_on:
            - postgres
        volumes:
            - ./emails.csv:/data/emails.csv
        networks:
            - mynetwork


    app:
        build: ./       
        deploy:
            mode: replicated
            replicas: 1  
        environment:
            - DB_HOST=db  # Variable de entorno para conexión a la base de datos (Azure/local)
        depends_on:
            - db
        networks:
            - mynetwork


    mysql-exporter:
        container_name: mysql-exporter
        image: prom/mysqld-exporter
        command: 
            - --config.my-cnf=/cfg/.my.cnf
            - --mysqld.address=db:3306  # Exporta métricas de MySQL
        volumes:
            - "./.my.cnf:/cfg/.my.cnf"
        depends_on:
            - db
        ports:
            - 9104:9104  # Expone métricas en el puerto 9104
        networks:
            - mynetwork


    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - grafana-data:/var/lib/grafana  # Persistencia de datos de Grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000  # Interfaz de Grafana
        networks:
            - mynetwork

            
networks:
    mynetwork:
        driver: bridge
        name: mynetwork  # Definición de red personalizada

volumes:
    mysql_data:  # Volumen para persistencia de MySQL
    grafana-data:  # Volumen para persistencia de Grafana
