services:

    namenode:
        image: apache/hadoop:3 
        container_name: namenode
        hostname: namenode
        ports:
            - "9870:9870" # NameNode Web UI
        networks:
            - mynetwork
        env_file: "./config.txt"
        command: hdfs namenode

    datanode:
        image: apache/hadoop:3 
        hostname: datanode
        container_name: datanode
        depends_on: 
            - namenode
        networks:
            - mynetwork
        env_file: "./config.txt"
        command: hdfs datanode


    hive:
        image: apache/hive:3.1.3
        hostname: hive
        container_name: hive
        depends_on:
            - namenode 
        environment:
            - SERVICE_NAME=hiveserver2
        ports:
            - "10000:10000"  # Hive server2 port
            - "10002:10002"    # Hive Metastore port
        volumes:
            - ./userdata:/userdata
            - ./schemas:/schemas
        networks:
            - mynetwork
        command: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/init-hive.sh"]
    

    db:
        container_name: mydb
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root      
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: proyecto2
        healthcheck:  # sanity check de MySQL
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
        volumes:
            - ./init-scripts:/docker-entrypoint-initdb.d  # Script de inicialización
        ports:
            - "32001:3306"  
        networks:
            - mynetwork

    sqoop:
        image: dvoros/sqoop:latest
        container_name: sqoop
        depends_on:
            - db
            - namenode
        volumes:
            - ./jdbc:/jdbc  # Conector JDBC 
            - ./core-site.xml.template:/usr/local/hadoop/etc/hadoop/core-site.xml.template  # Sobrescribe core-site.xml.template
        ports:
            - "12000:12000"  # Puerto del servidor Sqoop
        networks:
            - mynetwork
        tty: true
        stdin_open: true

        
networks:
    mynetwork:
        driver: bridge
        name: mynetwork  # Definición de red personalizada



